sonar.projectKey=DXF-Renewed
sonar.projectName=DXF-Renewed
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,lib/**,dist/**,coverage/**,src/nest/**/*.cjs,test/functional/**
sonar.test.inclusions=test/**/*.ts
sonar.typescript.tsconfigPath=tsconfig.json
